POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "Renato Portaluppi",
    "email": "renato@gmail.com",
    "password": "123renato"
}

###

GET http://localhost:3003/users

###

POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "esátua Reinato",
    "price": 99,
    "image_url": "www.gremio.net"
}