CREATE TABLE users_cookenu (
	id VARCHAR(255) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
	role ENUM("NORMAL", "ADMIN") DEFAULT "NORMAL"
);

SELECT * FROM users_cookenu;

DROP TABLE users_cookenu;