export const pokemonList = [

  {
    "Row": 1,
    "Name": "Bulbasaur",
    "Pokedex Number": 1,
    "Img name": 1,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 1,
    "Cross Gen": 0,
    "Type 1": "grass",
    "Type 2": "poison",
    "Weather 1": "Sunny/clear",
    "Weather 2": "Cloudy",
    "STAT TOTAL": 326,
    "ATK": 118,
    "DEF": 118,
    "STA": 90,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 5,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 981,
    "100% CP @ 39": 967
  },
  {
    "Row": 2,
    "Name": "Ivysaur",
    "Pokedex Number": 2,
    "Img name": 2,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 0,
    "FamilyID": 1,
    "Cross Gen": 0,
    "Type 1": "grass",
    "Type 2": "poison",
    "Weather 1": "Sunny/clear",
    "Weather 2": "Cloudy",
    "STAT TOTAL": 422,
    "ATK": 151,
    "DEF": 151,
    "STA": 120,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1552,
    "100% CP @ 39": 1529
  },
  {
    "Row": 3,
    "Name": "Venusaur",
    "Pokedex Number": 3,
    "Img name": 3,
    "Generation": 1,
    "Evolution Stage": 3,
    "Evolved": 1,
    "FamilyID": 1,
    "Cross Gen": 0,
    "Type 1": "grass",
    "Type 2": "poison",
    "Weather 1": "Sunny/clear",
    "Weather 2": "Cloudy",
    "STAT TOTAL": 556,
    "ATK": 198,
    "DEF": 198,
    "STA": 160,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 2568,
    "100% CP @ 39": 2531
  },
  {
    "Row": 4,
    "Name": "Charmander",
    "Pokedex Number": 4,
    "Img name": 4,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 2,
    "Cross Gen": 0,
    "Type 1": "fire",
    "Type 2": "",
    "Weather 1": "Sunny/clear",
    "Weather 2": "",
    "STAT TOTAL": 290,
    "ATK": 116,
    "DEF": 96,
    "STA": 78,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 5,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 831,
    "100% CP @ 39": 819
  },
  {
    "Row": 5,
    "Name": "Charmeleon",
    "Pokedex Number": 5,
    "Img name": 5,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 0,
    "FamilyID": 2,
    "Cross Gen": 0,
    "Type 1": "fire",
    "Type 2": "",
    "Weather 1": "Sunny/clear",
    "Weather 2": "",
    "STAT TOTAL": 403,
    "ATK": 158,
    "DEF": 129,
    "STA": 116,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1484,
    "100% CP @ 39": 1462
  },
  {
    "Row": 6,
    "Name": "Charizard",
    "Pokedex Number": 6,
    "Img name": 6,
    "Generation": 1,
    "Evolution Stage": 3,
    "Evolved": 1,
    "FamilyID": 2,
    "Cross Gen": 0,
    "Type 1": "fire",
    "Type 2": "flying",
    "Weather 1": "Sunny/clear",
    "Weather 2": "Windy",
    "STAT TOTAL": 555,
    "ATK": 223,
    "DEF": 176,
    "STA": 156,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 2686,
    "100% CP @ 39": 2648
  },
  {
    "Row": 7,
    "Name": "Squirtle",
    "Pokedex Number": 7,
    "Img name": 7,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 3,
    "Cross Gen": 0,
    "Type 1": "water",
    "Type 2": "",
    "Weather 1": "Rainy",
    "Weather 2": "",
    "STAT TOTAL": 304,
    "ATK": 94,
    "DEF": 122,
    "STA": 88,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 5,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 808,
    "100% CP @ 39": 797
  },
  {
    "Row": 8,
    "Name": "Wartortle",
    "Pokedex Number": 8,
    "Img name": 8,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 0,
    "FamilyID": 3,
    "Cross Gen": 0,
    "Type 1": "water",
    "Type 2": "",
    "Weather 1": "Rainy",
    "Weather 2": "",
    "STAT TOTAL": 399,
    "ATK": 126,
    "DEF": 155,
    "STA": 118,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1324,
    "100% CP @ 39": 1305
  },
  {
    "Row": 9,
    "Name": "Blastoise",
    "Pokedex Number": 9,
    "Img name": 9,
    "Generation": 1,
    "Evolution Stage": 3,
    "Evolved": 1,
    "FamilyID": 3,
    "Cross Gen": 0,
    "Type 1": "water",
    "Type 2": "",
    "Weather 1": "Rainy",
    "Weather 2": "",
    "STAT TOTAL": 539,
    "ATK": 171,
    "DEF": 210,
    "STA": 158,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 2291,
    "100% CP @ 39": 2259
  },
  {
    "Row": 10,
    "Name": "Caterpie",
    "Pokedex Number": 10,
    "Img name": 10,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 4,
    "Cross Gen": 0,
    "Type 1": "bug",
    "Type 2": "",
    "Weather 1": "Rainy",
    "Weather 2": "",
    "STAT TOTAL": 207,
    "ATK": 55,
    "DEF": 62,
    "STA": 90,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 393,
    "100% CP @ 39": 387
  },
  {
    "Row": 11,
    "Name": "Metapod",
    "Pokedex Number": 11,
    "Img name": 11,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 0,
    "FamilyID": 4,
    "Cross Gen": 0,
    "Type 1": "bug",
    "Type 2": "",
    "Weather 1": "Rainy",
    "Weather 2": "",
    "STAT TOTAL": 239,
    "ATK": 45,
    "DEF": 94,
    "STA": 100,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 419,
    "100% CP @ 39": 413
  },
  {
    "Row": 12,
    "Name": "Butterfree",
    "Pokedex Number": 12,
    "Img name": 12,
    "Generation": 1,
    "Evolution Stage": 3,
    "Evolved": 0,
    "FamilyID": 4,
    "Cross Gen": 0,
    "Type 1": "bug",
    "Type 2": "flying",
    "Weather 1": "Rainy",
    "Weather 2": "Windy",
    "STAT TOTAL": 438,
    "ATK": 167,
    "DEF": 151,
    "STA": 120,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1701,
    "100% CP @ 39": 1677
  },
  {
    "Row": 13,
    "Name": "Weedle",
    "Pokedex Number": 13,
    "Img name": 13,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 5,
    "Cross Gen": 0,
    "Type 1": "bug",
    "Type 2": "poison",
    "Weather 1": "Rainy",
    "Weather 2": "Cloudy",
    "STAT TOTAL": 198,
    "ATK": 63,
    "DEF": 55,
    "STA": 80,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 397,
    "100% CP @ 39": 391
  },
  {
    "Row": 14,
    "Name": "Kakuna",
    "Pokedex Number": 14,
    "Img name": 14,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 0,
    "FamilyID": 5,
    "Cross Gen": 0,
    "Type 1": "bug",
    "Type 2": "poison",
    "Weather 1": "Rainy",
    "Weather 2": "Cloudy",
    "STAT TOTAL": 222,
    "ATK": 46,
    "DEF": 86,
    "STA": 90,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 392,
    "100% CP @ 39": 386
  },
  {
    "Row": 15,
    "Name": "Beedrill",
    "Pokedex Number": 15,
    "Img name": 15,
    "Generation": 1,
    "Evolution Stage": 3,
    "Evolved": 0,
    "FamilyID": 5,
    "Cross Gen": 0,
    "Type 1": "bug",
    "Type 2": "poison",
    "Weather 1": "Rainy",
    "Weather 2": "Cloudy",
    "STAT TOTAL": 449,
    "ATK": 169,
    "DEF": 150,
    "STA": 130,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1777,
    "100% CP @ 39": 1752
  },
  {
    "Row": 16,
    "Name": "Pidgey",
    "Pokedex Number": 16,
    "Img name": 16,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 6,
    "Cross Gen": 0,
    "Type 1": "normal",
    "Type 2": "flying",
    "Weather 1": "Partly cloudy",
    "Weather 2": "Windy",
    "STAT TOTAL": 241,
    "ATK": 85,
    "DEF": 76,
    "STA": 80,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 580,
    "100% CP @ 39": 572
  },
  {
    "Row": 17,
    "Name": "Pidgeotto",
    "Pokedex Number": 17,
    "Img name": 17,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 0,
    "FamilyID": 6,
    "Cross Gen": 0,
    "Type 1": "normal",
    "Type 2": "flying",
    "Weather 1": "Partly cloudy",
    "Weather 2": "Windy",
    "STAT TOTAL": 351,
    "ATK": 117,
    "DEF": 108,
    "STA": 126,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1085,
    "100% CP @ 39": 1070
  },
  {
    "Row": 18,
    "Name": "Pidgeot",
    "Pokedex Number": 18,
    "Img name": 18,
    "Generation": 1,
    "Evolution Stage": 3,
    "Evolved": 0,
    "FamilyID": 6,
    "Cross Gen": 0,
    "Type 1": "normal",
    "Type 2": "flying",
    "Weather 1": "Partly cloudy",
    "Weather 2": "Windy",
    "STAT TOTAL": 489,
    "ATK": 166,
    "DEF": 157,
    "STA": 166,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1994,
    "100% CP @ 39": 1966
  },
  {
    "Row": 19,
    "Name": "Rattata",
    "Pokedex Number": 19,
    "Img name": 19,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 7,
    "Cross Gen": 0,
    "Type 1": "normal",
    "Type 2": "",
    "Weather 1": "Partly cloudy",
    "Weather 2": "",
    "STAT TOTAL": 233,
    "ATK": 103,
    "DEF": 70,
    "STA": 60,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 588,
    "100% CP @ 39": 580
  },
  {
    "Row": 20,
    "Name": "Raticate",
    "Pokedex Number": 20,
    "Img name": 20,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 0,
    "FamilyID": 7,
    "Cross Gen": 0,
    "Type 1": "normal",
    "Type 2": "",
    "Weather 1": "Partly cloudy",
    "Weather 2": "",
    "STAT TOTAL": 415,
    "ATK": 161,
    "DEF": 144,
    "STA": 110,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1549,
    "100% CP @ 39": 1527
  },
  {
    "Row": 21,
    "Name": "Spearow",
    "Pokedex Number": 21,
    "Img name": 21,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 8,
    "Cross Gen": 0,
    "Type 1": "normal",
    "Type 2": "flying",
    "Weather 1": "Partly cloudy",
    "Weather 2": "Windy",
    "STAT TOTAL": 253,
    "ATK": 112,
    "DEF": 61,
    "STA": 80,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 673,
    "100% CP @ 39": 664
  },
  {
    "Row": 22,
    "Name": "Fearow",
    "Pokedex Number": 22,
    "Img name": 22,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 1,
    "FamilyID": 8,
    "Cross Gen": 0,
    "Type 1": "normal",
    "Type 2": "flying",
    "Weather 1": "Partly cloudy",
    "Weather 2": "Windy",
    "STAT TOTAL": 447,
    "ATK": 182,
    "DEF": 135,
    "STA": 130,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1814,
    "100% CP @ 39": 1788
  },
  {
    "Row": 23,
    "Name": "Ekans",
    "Pokedex Number": 23,
    "Img name": 23,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 9,
    "Cross Gen": 0,
    "Type 1": "poison",
    "Type 2": "",
    "Weather 1": "Cloudy",
    "Weather 2": "",
    "STAT TOTAL": 282,
    "ATK": 110,
    "DEF": 102,
    "STA": 70,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 778,
    "100% CP @ 39": 767
  },
  {
    "Row": 24,
    "Name": "Arbok",
    "Pokedex Number": 24,
    "Img name": 24,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 1,
    "FamilyID": 9,
    "Cross Gen": 0,
    "Type 1": "poison",
    "Type 2": "",
    "Weather 1": "Cloudy",
    "Weather 2": "",
    "STAT TOTAL": 445,
    "ATK": 167,
    "DEF": 158,
    "STA": 120,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1737,
    "100% CP @ 39": 1712
  },
  {
    "Row": 25,
    "Name": "Pikachu",
    "Pokedex Number": 25,
    "Img name": 25,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 10,
    "Cross Gen": 0,
    "Type 1": "electric",
    "Type 2": "",
    "Weather 1": "Rainy",
    "Weather 2": "",
    "STAT TOTAL": 283,
    "ATK": 112,
    "DEF": 101,
    "STA": 70,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 1,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 787,
    "100% CP @ 39": 776
  },
  {
    "Row": 26,
    "Name": "Raichu",
    "Pokedex Number": 26,
    "Img name": 26,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 1,
    "FamilyID": 10,
    "Cross Gen": 0,
    "Type 1": "electric",
    "Type 2": "",
    "Weather 1": "Rainy",
    "Weather 2": "",
    "STAT TOTAL": 478,
    "ATK": 193,
    "DEF": 165,
    "STA": 120,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 1,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 2025,
    "100% CP @ 39": 1996
  },
  {
    "Row": 27,
    "Name": "Sandshrew",
    "Pokedex Number": 27,
    "Img name": 27,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 11,
    "Cross Gen": 0,
    "Type 1": "ground",
    "Type 2": "",
    "Weather 1": "Sunny/clear",
    "Weather 2": "",
    "STAT TOTAL": 371,
    "ATK": 126,
    "DEF": 145,
    "STA": 100,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1194,
    "100% CP @ 39": 1177
  },
  {
    "Row": 28,
    "Name": "Sandslash",
    "Pokedex Number": 28,
    "Img name": 28,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 1,
    "FamilyID": 11,
    "Cross Gen": 0,
    "Type 1": "ground",
    "Type 2": "",
    "Weather 1": "Sunny/clear",
    "Weather 2": "",
    "STAT TOTAL": 534,
    "ATK": 182,
    "DEF": 202,
    "STA": 150,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 2328,
    "100% CP @ 39": 2294
  },
  {
    "Row": 29,
    "Name": "Nidoran F",
    "Pokedex Number": 29,
    "Img name": 29,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 12,
    "Cross Gen": 0,
    "Type 1": "poison",
    "Type 2": "",
    "Weather 1": "Cloudy",
    "Weather 2": "",
    "STAT TOTAL": 290,
    "ATK": 86,
    "DEF": 94,
    "STA": 110,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 736,
    "100% CP @ 39": 725
  },
  {
    "Row": 30,
    "Name": "Nidorina",
    "Pokedex Number": 30,
    "Img name": 30,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 0,
    "FamilyID": 12,
    "Cross Gen": 0,
    "Type 1": "poison",
    "Type 2": "",
    "Weather 1": "Cloudy",
    "Weather 2": "",
    "STAT TOTAL": 383,
    "ATK": 117,
    "DEF": 126,
    "STA": 140,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1218,
    "100% CP @ 39": 1201
  },
  {
    "Row": 31,
    "Name": "Nidoqueen",
    "Pokedex Number": 31,
    "Img name": 31,
    "Generation": 1,
    "Evolution Stage": 3,
    "Evolved": 1,
    "FamilyID": 12,
    "Cross Gen": 0,
    "Type 1": "poison",
    "Type 2": "ground",
    "Weather 1": "Cloudy",
    "Weather 2": "Sunny/clear",
    "STAT TOTAL": 534,
    "ATK": 180,
    "DEF": 174,
    "STA": 180,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 2338,
    "100% CP @ 39": 2304
  },
  {
    "Row": 32,
    "Name": "Nidoran M",
    "Pokedex Number": 32,
    "Img name": 32,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 13,
    "Cross Gen": 0,
    "Type 1": "poison",
    "Type 2": "",
    "Weather 1": "Cloudy",
    "Weather 2": "",
    "STAT TOTAL": 273,
    "ATK": 105,
    "DEF": 76,
    "STA": 92,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 739,
    "100% CP @ 39": 729
  },
  {
    "Row": 33,
    "Name": "Nidorino",
    "Pokedex Number": 33,
    "Img name": 33,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 0,
    "FamilyID": 13,
    "Cross Gen": 0,
    "Type 1": "poison",
    "Type 2": "",
    "Weather 1": "Cloudy",
    "Weather 2": "",
    "STAT TOTAL": 371,
    "ATK": 137,
    "DEF": 112,
    "STA": 122,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1252,
    "100% CP @ 39": 1234
  },
  {
    "Row": 34,
    "Name": "Nidoking",
    "Pokedex Number": 34,
    "Img name": 34,
    "Generation": 1,
    "Evolution Stage": 3,
    "Evolved": 1,
    "FamilyID": 13,
    "Cross Gen": 0,
    "Type 1": "poison",
    "Type 2": "ground",
    "Weather 1": "Cloudy",
    "Weather 2": "Sunny/clear",
    "STAT TOTAL": 523,
    "ATK": 204,
    "DEF": 157,
    "STA": 162,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 2386,
    "100% CP @ 39": 2352
  },
  {
    "Row": 35,
    "Name": "Clefairy",
    "Pokedex Number": 35,
    "Img name": 35,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 14,
    "Cross Gen": 0,
    "Type 1": "fairy",
    "Type 2": "",
    "Weather 1": "Cloudy",
    "Weather 2": "",
    "STAT TOTAL": 363,
    "ATK": 107,
    "DEF": 116,
    "STA": 140,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1085,
    "100% CP @ 39": 1070
  },
  {
    "Row": 36,
    "Name": "Clefable",
    "Pokedex Number": 36,
    "Img name": 36,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 1,
    "FamilyID": 14,
    "Cross Gen": 0,
    "Type 1": "fairy",
    "Type 2": "",
    "Weather 1": "Cloudy",
    "Weather 2": "",
    "STAT TOTAL": 539,
    "ATK": 178,
    "DEF": 171,
    "STA": 190,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 2353,
    "100% CP @ 39": 2320
  },
  {
    "Row": 37,
    "Name": "Vulpix",
    "Pokedex Number": 37,
    "Img name": 37,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 15,
    "Cross Gen": 0,
    "Type 1": "fire",
    "Type 2": "",
    "Weather 1": "Sunny/clear",
    "Weather 2": "",
    "STAT TOTAL": 294,
    "ATK": 96,
    "DEF": 122,
    "STA": 76,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 774,
    "100% CP @ 39": 763
  },
  {
    "Row": 38,
    "Name": "Ninetales",
    "Pokedex Number": 38,
    "Img name": 38,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 1,
    "FamilyID": 15,
    "Cross Gen": 0,
    "Type 1": "fire",
    "Type 2": "",
    "Weather 1": "Sunny/clear",
    "Weather 2": "",
    "STAT TOTAL": 519,
    "ATK": 169,
    "DEF": 204,
    "STA": 146,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 2157,
    "100% CP @ 39": 2127
  },
  {
    "Row": 39,
    "Name": "Jigglypuff",
    "Pokedex Number": 39,
    "Img name": 39,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 16,
    "Cross Gen": 0,
    "Type 1": "normal",
    "Type 2": "fairy",
    "Weather 1": "Partly cloudy",
    "Weather 2": "Cloudy",
    "STAT TOTAL": 354,
    "ATK": 80,
    "DEF": 44,
    "STA": 230,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 713,
    "100% CP @ 39": 703
  },
  {
    "Row": 40,
    "Name": "Wigglytuff",
    "Pokedex Number": 40,
    "Img name": 40,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 1,
    "FamilyID": 16,
    "Cross Gen": 0,
    "Type 1": "normal",
    "Type 2": "fairy",
    "Weather 1": "Partly cloudy",
    "Weather 2": "Cloudy",
    "STAT TOTAL": 529,
    "ATK": 156,
    "DEF": 93,
    "STA": 280,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1906,
    "100% CP @ 39": 1879
  },
  {
    "Row": 41,
    "Name": "Zubat",
    "Pokedex Number": 41,
    "Img name": 41,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 17,
    "Cross Gen": 0,
    "Type 1": "poison",
    "Type 2": "flying",
    "Weather 1": "Cloudy",
    "Weather 2": "Windy",
    "STAT TOTAL": 239,
    "ATK": 83,
    "DEF": 76,
    "STA": 80,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 569,
    "100% CP @ 39": 560
  },
  {
    "Row": 42,
    "Name": "Golbat",
    "Pokedex Number": 42,
    "Img name": 42,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 0,
    "FamilyID": 17,
    "Cross Gen": 0,
    "Type 1": "poison",
    "Type 2": "flying",
    "Weather 1": "Cloudy",
    "Weather 2": "Windy",
    "STAT TOTAL": 464,
    "ATK": 161,
    "DEF": 153,
    "STA": 150,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1830,
    "100% CP @ 39": 1804
  },
  {
    "Row": 43,
    "Name": "Oddish",
    "Pokedex Number": 43,
    "Img name": 43,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 18,
    "Cross Gen": 0,
    "Type 1": "grass",
    "Type 2": "poison",
    "Weather 1": "Sunny/clear",
    "Weather 2": "Cloudy",
    "STAT TOTAL": 337,
    "ATK": 131,
    "DEF": 116,
    "STA": 90,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 2,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1069,
    "100% CP @ 39": 1054
  },
  {
    "Row": 44,
    "Name": "Gloom",
    "Pokedex Number": 44,
    "Img name": 44,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 0,
    "FamilyID": 18,
    "Cross Gen": 0,
    "Type 1": "grass",
    "Type 2": "poison",
    "Weather 1": "Sunny/clear",
    "Weather 2": "Cloudy",
    "STAT TOTAL": 412,
    "ATK": 153,
    "DEF": 139,
    "STA": 120,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1512,
    "100% CP @ 39": 1491
  },
  {
    "Row": 45,
    "Name": "Vileplume",
    "Pokedex Number": 45,
    "Img name": 45,
    "Generation": 1,
    "Evolution Stage": 3,
    "Evolved": 1,
    "FamilyID": 18,
    "Cross Gen": 0,
    "Type 1": "grass",
    "Type 2": "poison",
    "Weather 1": "Sunny/clear",
    "Weather 2": "Cloudy",
    "STAT TOTAL": 522,
    "ATK": 202,
    "DEF": 170,
    "STA": 150,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 2367,
    "100% CP @ 39": 2334
  },
  {
    "Row": 46,
    "Name": "Paras",
    "Pokedex Number": 46,
    "Img name": 46,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 19,
    "Cross Gen": 0,
    "Type 1": "bug",
    "Type 2": "grass",
    "Weather 1": "Rainy",
    "Weather 2": "Sunny/clear",
    "STAT TOTAL": 290,
    "ATK": 121,
    "DEF": 99,
    "STA": 70,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 836,
    "100% CP @ 39": 824
  },
  {
    "Row": 47,
    "Name": "Parasect",
    "Pokedex Number": 47,
    "Img name": 47,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 1,
    "FamilyID": 19,
    "Cross Gen": 0,
    "Type 1": "bug",
    "Type 2": "grass",
    "Weather 1": "Rainy",
    "Weather 2": "Sunny/clear",
    "STAT TOTAL": 431,
    "ATK": 165,
    "DEF": 146,
    "STA": 120,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1657,
    "100% CP @ 39": 1633
  },
  {
    "Row": 48,
    "Name": "Venonat",
    "Pokedex Number": 48,
    "Img name": 48,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 20,
    "Cross Gen": 0,
    "Type 1": "bug",
    "Type 2": "poison",
    "Weather 1": "Rainy",
    "Weather 2": "Cloudy",
    "STAT TOTAL": 322,
    "ATK": 100,
    "DEF": 102,
    "STA": 120,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 902,
    "100% CP @ 39": 889
  },
  {
    "Row": 49,
    "Name": "Venomoth",
    "Pokedex Number": 49,
    "Img name": 49,
    "Generation": 1,
    "Evolution Stage": 2,
    "Evolved": 1,
    "FamilyID": 20,
    "Cross Gen": 0,
    "Type 1": "bug",
    "Type 2": "poison",
    "Weather 1": "Rainy",
    "Weather 2": "Cloudy",
    "STAT TOTAL": 469,
    "ATK": 179,
    "DEF": 150,
    "STA": 140,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 0,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 1937,
    "100% CP @ 39": 1910
  },
  {
    "Row": 50,
    "Name": "Diglett",
    "Pokedex Number": 50,
    "Img name": 50,
    "Generation": 1,
    "Evolution Stage": 1,
    "Evolved": 0,
    "FamilyID": 21,
    "Cross Gen": 0,
    "Type 1": "ground",
    "Type 2": "",
    "Weather 1": "Sunny/clear",
    "Weather 2": "",
    "STAT TOTAL": 217,
    "ATK": 109,
    "DEF": 88,
    "STA": 20,
    "Legendary": 0,
    "Aquireable": 1,
    "Spawns": 1,
    "Regional": 0,
    "Raidable": 0,
    "Hatchable": 0,
    "Shiny": 0,
    "Nest": 1,
    "New": 0,
    "Not-Gettable": 0,
    "Future Evolve": 0,
    "100% CP @ 40": 465,
    "100% CP @ 39": 458
  },
]